name: 'agentsec - AI Agent Security Scanner'
description: 'Scan agentic AI installations for security misconfigurations. Maps findings to OWASP Top 10 for Agentic Applications.'
author: 'Debu Sinha'

branding:
  icon: 'shield'
  color: 'orange'

inputs:
  target:
    description: 'Path to scan'
    required: false
    default: '.'
  fail-on:
    description: 'Minimum severity to fail the build (critical, high, medium, low, info, none)'
    required: false
    default: 'high'
  output:
    description: 'Output format (terminal, json, sarif)'
    required: false
    default: 'sarif'
  output-file:
    description: 'File path for scan results'
    required: false
    default: 'results.sarif'
  scanners:
    description: 'Comma-separated scanner list (installation, skill, mcp, credential). Default: all'
    required: false
    default: ''
  version:
    description: 'agentsec-ai version to install (e.g. "0.4.4"). Empty = latest.'
    required: false
    default: ''
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install agentsec
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        if [ -n "$INPUT_VERSION" ]; then
          pip install "agentsec-ai==$INPUT_VERSION"
        else
          pip install agentsec-ai
        fi

    - name: Run security scan
      id: scan
      shell: bash
      env:
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_FAIL_ON: ${{ inputs.fail-on }}
        INPUT_OUTPUT_FILE: ${{ inputs.output-file }}
        INPUT_SCANNERS: ${{ inputs.scanners }}
      run: |
        set -- "$INPUT_TARGET" -o "$INPUT_OUTPUT" --fail-on "$INPUT_FAIL_ON"

        if [ -n "$INPUT_OUTPUT_FILE" ]; then
          set -- "$@" -f "$INPUT_OUTPUT_FILE"
        fi

        if [ -n "$INPUT_SCANNERS" ]; then
          set -- "$@" -s "$INPUT_SCANNERS"
        fi

        agentsec scan "$@"

    - name: Upload SARIF to GitHub Code Scanning
      if: ${{ always() && inputs.upload-sarif == 'true' && inputs.output == 'sarif' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.output-file }}
